spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: catapract
  datasource:
    url: "jdbc:postgresql://localhost:5432/catapract_db"
    username: "postgres"
    password: "DucPhuc2"
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 
  expiration-ms: 3600000